colors =["red","green","blue"]
# colors_iter = iter(colors)
# color = next(colors_iter)
# print(color)
# color = next(colors_iter)
# print(color)
# color = next(colors_iter)
# print(color)
# color = next(colors_iter)
# print(color)

color_iter = iter(colors)
color = next(color_iter)
print(color)
color = next(color_iter)
print(color)